pipeline 
{

    agent any

    stages 
    {
        stage('Connection test') 
        {
            steps 
            { 
                script 
                {

                    print  "Hello Vasili"                    
                    sh 'ssh root@18.184.89.157 apt-get update -y'
                    print  "vagrant Instaled!!"  
                    
                    print  "Webhooks it's works!"  
                }                
            }
        }
    }
}
