pipeline 
{

    agent any

    stages 
    {
        stage('Connection test') 
        {
            steps 
            { 
                script 
                {

                    print  "Hello Vasili"                    
                    sh 'ssh root@3.121.184.54 uptime'
                }                
            }
        }
    }
}
